@baseURL = https://dev.hivelighter.com

### Auth

# @name register
POST {{baseURL}}/register/automaticEmailAccount
Content-Type: application/json

{
    "email": "test@email.com",
    "fullname": "Test User",
    "password": "qwerty"
}

###

# @name login
POST {{baseURL}}/register/login/checkPassword
Content-Type: application/json

{
    "email": "test@email.com",
    "password": "qwerty"
}

### Profile

# @name profile
GET {{baseURL}}/api/profile
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

{
    "uuid": "575fd091-000e-0358-871b-ec9b66736712"
}

#### Get my profile in JSON format

# @name profileJSON
GET {{baseURL}}/api/profile-json
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

#### Update my profile except avatar

# @name updateProfileJSON
POST {{baseURL}}/api/profile-json
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

{
    "username": "Hey_User_0uv6r",
    "firstname": "Hey",
    "lastname": "User",
    "bio": "Hey user is the developer of this service."
}

#### Update my name

# @name updateName
POST {{baseURL}}/api/updateProfileFirstnameLastname
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

{
    "firstname": "Hey",
    "lastname": "User"
}

#### Update my user name

# @name setUserName
POST {{baseURL}}/api/setUsername
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

{
    "username": "New_User_0uv6r"
}

#### Update my Bio

# @name setBio
PUT {{baseURL}}/api/setUserBio
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

{
    "bio": "I am the developer of this service. updated without uuid"
}

#### Get Profile of the specified user, provide the user id as a query parameter

# @name userProfile
GET {{baseURL}}/api/userProfile?uuid=8857e556-54a2-0d5b-88f2-945d265827ab
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY


### Shares

#### Everyone - All published contents from someone elses

# @name publishedFromOtherUsers
GET {{baseURL}}/api/publishedFromOtherUsers?newer=false
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

#### Me - All published contents from a person, use actorId as my id to get my publishes

# @name publishedFromActor
GET {{baseURL}}/api/publishedFromActor?newer=1&actorId=575fd091-000e-0358-871b-ec9b66736712
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

#### My Swarm - All published contents from users that I follow

# @name publishedFromUsersIFollow
GET {{baseURL}}/api/publishedFromUsersIFollow?newer=false
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY


### Blocking

####

# @name fetchBlockUsers
GET {{baseURL}}/api/fetchBlockedUsers
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

####

# @name blockUser
POST {{baseURL}}/api/blockUser
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

{
    "user_id": "8857e556-54a2-0d5b-88f2-945d265827ab"
}

####

# @name unblockUser
DELETE {{baseURL}}/api/unblockUser/8857e556-54a2-0d5b-88f2-945d265827ab
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY


### Following

#### Get all persons that the specified user follows, provide uuid as the user id

# @name getFollowing
GET {{baseURL}}/api/getFollowing?newer=0&uuid=8857e556-54a2-0d5b-88f2-945d265827ab
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

#### Get all persons that follow the specified user, provide uuid as the user id

# @name getFollowers
GET {{baseURL}}/api/getFollowers?newer=0&uuid=8857e556-54a2-0d5b-88f2-945d265827ab
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

#### Get followers and following count related to me

# @name getFollowerData
GET {{baseURL}}/api/getFollowerData
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

#### Follow/Unfolow a person, provide follow as true or false

# @name followUser
POST {{baseURL}}/api/follow
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

{
    "user_id": "8857e556-54a2-0d5b-88f2-945d265827ab",
    "follow": true
}

### Notification

#### Get Notifications

# @name notifications
GET {{baseURL}}/api/notifications?newer=0
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

#### Get NotificationCount

# @name notificationsCount
GET {{baseURL}}/api/notificationsCount
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTc1ZmQwOTEtMDAwZS0wMzU4LTg3MWItZWM5YjY2NzM2NzEyIiwicktleSI6IjFiNGQ2ZWY1ZjNjOGQ4ODBjYTAzODYxYWNmODQzNzIwYWJlNTJhYjEiLCJpYXQiOjE2MDI3NDY1MTYsImV4cCI6MzMxMzg3NDY1MTZ9.StIpVkX6obkXn3hgyVysXs5KetAXPqQp6YyZ9_kWGsY

### Routes

// Set username
apiRoutes.post('/setUsername', service.api_setUserName);

// Set bio
apiRoutes.put('/setUserBio', service.api_setUserBio);

// Version Global Notification
apiRoutes.post('/global_notification', service.api_global_notification);

// post/delete blocked user
apiRoutes.get('/fetchBlockedUsers', service.api_fetchBlockedUsers);
apiRoutes.post('/blockUser', service.api_blockUser);
apiRoutes.delete('/unblockUser/:blockedUserId', service.api_unblockUser);

// get user profile
apiRoutes.get('/userProfile', service.api_getUserProfile);
apiRoutes.post('/updateProfileFirstnameLastname', service.api_updateProfileFirstnameLastname);

// Handle user profile pics
apiRoutes.get('/setUserPic', service.api_setUserPic);
apiRoutes.post('/setUserPicUpload', upload.fields([{name: "thumb"}, {name: "thumb-200"}, {name: "originImage"}]), service.api_setUserPicUpload);

// notification routes
apiRoutes.get('/notifications', service.api_getNotifications);
apiRoutes.get('/notificationsCount', service.api_getNotificationsCount);

// like
apiRoutes.get('/getLikeCount', service.api_getLikeCount);
apiRoutes.post('/like', service.api_handlePublishedPageLike);

// follow
apiRoutes.get('/getFollowersCount', service.api_getFollowersCount);
apiRoutes.get('/getFollowing', service.api_getFollowing);
apiRoutes.get('/getFollowers', service.api_getFollowers);
apiRoutes.post('/follow', service.api_handleUserFollow);
// get following and followers count
apiRoutes.get('/getFollowerData', service.api_getFollowerData);
// Settings:
apiRoutes.get('/profile', service.api_getMyProfile); // My profile
// User:
apiRoutes.get('/partialProfile', service.api_getUserPartialProfile); // My profile
apiRoutes.get('/creationTime', service.api_creationTime);

// API: Handle rect in source profile image
apiRoutes.get('/fetchRectOfProfilePicWithinSourceProfileImage', service.api_fetchRectOfProfilePicWithinSourceProfileImage);
apiRoutes.post('/storeRectOfProfilePicWithinSourceProfileImage', service.api_storeRectOfProfilePicWithinSourceProfileImage);
